services:
  kafka:
    image: confluentinc/cp-kafka:8.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5

  bridge:
    build: ./bridge
    container_name: bridge
    ports:
      - "4000:4000"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-net

  consumer:
    build: ./consumer
    container_name: consumer
    ports:
      - "5075:5075"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-net

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - consumer
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge